name: Build Node.js SPAs

on:
  workflow_call:
    inputs:
      nodeVersion:
        required: true
        type: string
      artifactPath:
        required: false
        type: string
        default: "dist"
      artifactName:
        required: false
        type: string
        default: "dist"
      commitHash:
        required: false
        type: string
        default: ${{ github.sha }}
      retentionDays:
        required: false
        type: number
        default: 45
      path:
        required: false
        type: string
        default: ${GITHUB_WORKSPACE}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
      - run: npm install
      - run: npm run lint --if-present
      - run: npm run test --if-present
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
      - name: Download Env artifacts
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R -a
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
      - run: npm install
      - run: npm run build
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          retention-days: ${{ inputs.retentionDays }}
