name: Build Node.js SPAs

on:
  workflow_call:
    inputs:
      nodeVersion:
        required: true
        type: string
    commitHash:
        required: false
        type: string
        default: ${{ github.sha }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
      - run: npm install
      - run: npm run lint --if-present 
      - run: npm run test --if-present
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
      - run: npm install
      - run: npm run build
      
