name: Create enviroment file   

on:
  workflow_call:
    inputs:      
      artifactName:
        required: false
        type: string
        default: "env"
      artifactPath:
        required: false
        type: string
    secrets:
      envBase64:
        required: true
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create env file        
        run: |
          [ -n "${{ inputs.artifactPath }}" ] && mkdir -p ${{ inputs.artifactPath }}
          [ -n "${{ inputs.artifactPath }}" ] && cd ${{ inputs.artifactPath }}
          echo ${{ secrets.envBase64 }} | base64 --decode > .env 
      - name: Display structure of downloaded files
        run: ls -R -a
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ github.workspace }}
        
