name: Create enviroment file   

on:
  workflow_call:
    inputs:      
      path:
        required: false
        type: string
        default: ${GITHUB_WORKSPACE}
      artifactName:
        required: true
        type: string
        default: "env"
    secrets:
      envBase64:
        required: true
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create env file        
        run: |
          mkdir -p ${{ inputs.path }}
          cd ${{ inputs.path }}
          echo ${{ secrets.envBase64 }} | base64 --decode > .env 
      - name: Display structure of downloaded files
        run: ls -R -a
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ github.workspace }}
