name: Create enviroment file   

on:
  workflow_call:
    secrets:
      envBase64:
        required: true
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create env file        
        run: |
          echo ${{ secrets.envBase64 }} | base64 --decode > .env 
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: env
          path: |
            .env
