name: Deploy Firebase App

on:
  workflow_call:
    secrets:
      firebaseServiceAccount:
        required: true
      envBase64:
        required: true
    inputs:
      projectId: 
        required: true
        type: string         
      artifactId: 
        required: true
        type: number
jobs:
  deploy: 
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
      - name: Create env file        
        run: |
          echo ${{ secrets.envBase64 }} | base64 --decode > .env 
      - name: Install Scripts dependencies      
        run: npm --prefix  .github/scripts/download-artifacts install
      - name: Download artifacts        
        run: npm --prefix  .github/scripts/download-artifacts run download -- ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }} ${{ inputs.artifactId }}
      - name: Display structure of downloaded files
        run: ls -R     
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.firebaseServiceAccount }}'
          channelId: live
          projectId: '${{ inputs.projectId }}'