name: Deploy Firebase Functions

on:
  workflow_call:
    secrets:
      firebaseToken:
        required: true
    inputs:
      path:
        required: true
        type: string
        default: ${GITHUB_WORKSPACE}
      projectId:
        required: true
        type: string
      commitHash:
        required: false
        type: string
        default: ${{ github.sha }}
jobs:
  npm-deploy:
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }} 
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '11'
      - uses: actions/setup-node@v3
        with:
          node-version: 18        
      - name: Setup Firebase
        run: curl -sL https://firebase.tools | bash
      - name: Authenticate to GitHub Package Registry
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{ github.token }}' >> ~/.npmrc
          echo '@inncosys:registry=https://npm.pkg.github.com' >> ~/.npmrc
          npm config set -- '//npm.pkg.github.com/:_authToken' '${{ github.token }}'
      - name: Display structure of downloaded files
        run: |
         pwd
         ls -R -a
      - name: NPM Install
        run: npm install
        working-directory: ${{ inputs.path }}
      - name: Deploy
        run: |
          node -v
          npm -v
          npm run deploy -- --project ${{ inputs.projectId }} --token ${{ secrets.firebaseToken }}
        working-directory: ${{ inputs.path }}
