name: Deploy Firebase Functions

on:
  workflow_call:
    secrets:
      firebaseToken:
        required: true
    inputs:
      path:
        required: true
        type: string
        default: ${GITHUB_WORKSPACE}
      projectId:
        required: true
        type: string
      commitHash:
        required: false
        type: string
        default: ${{ github.sha }}
jobs:
  npm-deploy:
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    runs-on: ubuntu-latest
    container:
      image: inncosys/firebase-tools
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R -a
      - name: NPM Install
        run: npm install
      - name: Deploy
        run: npm run deploy -- --project ${{ inputs.projectId }} --token ${{ secrets.firebaseToken }}
