name: Deploy Firebase App

on:
  workflow_call:
    secrets:
      firebaseServiceAccount:
        required: true
      envBase64:
        required: true
    inputs:
      projectId: 
        required: true
        type: string         
      artifactId: 
        required: true
        type: number
jobs:
  deploy: 
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.firebaseServiceAccount }}'
          channelId: live
          projectId: '${{ inputs.projectId }}'