name: Deploy Firebase App Preview Channel

on:
  workflow_call:
    secrets:
      firebaseServiceAccount:
        required: true
      envDevBase64:
        required: true
      envStagingBase64:
        required: true
      envLiveBase64:
        required: true
    inputs:
      projectDevId: 
        required: true
        type: string
      projectStagingId: 
        required: true
        type: string
      projectLiveId: 
        required: true
        type: string
      
jobs:
  deploy: 
    name: Deploy Preview
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
      - name: Create env file        
        run: |
          echo ${{ secrets.envDevBase64 }} | base64 --decode > .env 
      - name: Display structure of downloaded files
        run: ls -R     
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.firebaseServiceAccount }}'
          channelId: live
          projectId: '${{ inputs.projectDevId }}'
