name: Deploy Firebase Functions

on:
  workflow_call:
    secrets:
      firebaseToken:
        required: true
    inputs:
      path:
        required: true
        type: string
        default: ${GITHUB_WORKSPACE} 
      projectId: 
        required: true
        type: string
jobs:
  npm-deploy:
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    runs-on: ubuntu-latest
    container:
      image: inncosys/firebase-tools:node16
    steps:
      - uses: actions/checkout@v3
      - name: Download All Artifacts
      - run: npm install
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R -a          
      - name: Deploy
        run: npm run deploy -- --project ${{ inputs.projectId }} --token ${{ secrets.firebaseToken }}
      