name: Deploy Firebase App

on:
  workflow_call:
    secrets:
      firebaseServiceAccount:
        required: true
      envBase64:
        required: true
    inputs:
      projectId: 
        required: true
        type: string      
jobs:
  deploy: 
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
      - name: Create env file        
        run: |
          echo ${{ secrets.envBase64 }} | base64 --decode > .env 
      - name: Display structure of downloaded files
        run: ls -R     
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.firebaseServiceAccount }}'
          channelId: live
          projectId: '${{ inputs.projectId }}'