name: Deploy Firebase App Preview Channel

on:
  workflow_call:
    secrets:
      firebaseServiceAccount:
        required: true
    inputs:
      projectId: 
        required: true
        type: string
      target: 
        required: false
        type: string
jobs:
  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R -a     
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.firebaseServiceAccount }}'
          projectId: '${{ inputs.projectId }}'
          target: '${{ inputs.target }}'
          channelId: live
