name: Build Node.js SPAs

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
        default: ${GITHUB_WORKSPACE} 
jobs:
  test:
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    runs-on: ubuntu-latest
    container:
      image: inncosys/firebase-tools:node16
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint --if-present 
      - run: npm run test --if-present